env:
  node: true

extends:
  - eslint:recommended
  - airbnb

globals:
  uneval: false

plugins:
  - mozilla

root: true

rules:
  import/newline-after-import: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off

  mozilla/balanced-listeners: off
  mozilla/no-aArgs: warn
  mozilla/this-top-level-scope: warn

  class-methods-use-this: off
  eqeqeq: error
  indent: [warn, 2, {SwitchCase: 1}]
  no-console: warn
  quotes: [error, single]
